const { app, BrowserWindow } = require('electron');
app.disableHardwareAcceleration();
app.setPath('userData', require('fs').mkdtempSync(require('path').join(require('os').tmpdir(), 'khata-ui-')));
const fs = require('fs');
const path = require('path');
const resultPath = path.join(__dirname, 'test_ui_result.json');
const timeout = setTimeout(() => { fs.writeFileSync(resultPath, JSON.stringify({ error: 'UI test timed out' })); app.exit(1); }, 30000);
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, webPreferences: { contextIsolation: true } });
  try {
    const html = fs.readFileSync(path.join(__dirname, 'renderer/index.html'), 'utf8')
      .replace('<script src="js/app.js"></script>', '')
      .replace('<link rel="stylesheet" href="css/styles.css">', () => '<style>' + fs.readFileSync(path.join(__dirname, 'renderer/css/styles.css'), 'utf8') + '</style>');
    await win.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html));
    await win.webContents.executeJavaScript(`
      window.failures = []; window.calls = []; window.downloads = [];
      window.addEventListener('error', e => failures.push(e.message));
      window.addEventListener('unhandledrejection', e => failures.push(String(e.reason)));
      window.bound = new Set();
      const originalListener = EventTarget.prototype.addEventListener;
      EventTarget.prototype.addEventListener = function(type, ...args) { if (this.id) bound.add(this.id + ':' + type); return originalListener.call(this, type, ...args); };
      HTMLAnchorElement.prototype.click = function() { downloads.push(this.download); };
      window.print = () => calls.push(['print']);
      window.confirmAnswer = false;
      window.confirm = message => { calls.push(['confirm', message]); return window.confirmAnswer; };
      const customer = { id: 1, account_code: '01', name: 'Test Customer', currency: 'AED', opening_balance: 0, opening_balance_type: 'Zero Balance', balance_cents: 0, status: 'Settled', is_archived: 0 };
      const summary = { receivable_cents: 0, payable_cents: 0, today_received_cents: 0, today_paid_cents: 0 };
      const settings = { business_name: 'Test Business', require_login: '0' };
      const report = { rows: [], aedTotals: { receivable: 0, payable: 0 }, pkrTotals: { receivable: 0, payable: 0 } };
      window.api = new Proxy({}, { get: (_, name) => async (...args) => {
        calls.push([name, ...args]);
        if (name === 'getSession') return { id: 1, name: 'Admin', role: 'Admin' };
        if (name === 'getSettings') return settings;
        if (name === 'getBackupStatus') return { frequency: 'Daily', lastSuccessAt: '2026-09-23T12:00:00Z', nextBackupAt: '2026-09-24T12:00:00Z', overdue: false, lastError: null };
        if (name === 'getTransactionById') return { id: 5, customer_id: 1, transaction_code: 'TRX-000005', transaction_date: '2026-01-01', transaction_type: 'Credit', amount: 12500, description: 'Original payment', payment_method: 'Cash', reference_number: 'REF5', notes: '' };
        if (name === 'updateTransaction') return { id: args[0], transaction_code: 'TRX-000005', ...args[1] };
        if (name === 'updateSettings') { Object.assign(settings, args[0]); return {}; }
        if (name === 'getDashboardData') return { total_customers: 1, today_transactions_count: 0, aed_summary: summary, pkr_summary: summary, recent_transactions: [] };
        if (name === 'getCustomers') return args[1] ? [customer, { ...customer, id: 2, name: 'Archived Customer', is_archived: 1 }] : [customer];
        if (name === 'getCustomerById' || name === 'createCustomer') return customer;
        if (name === 'peekNextAccountCode') return '02';
        if (name === 'getCustomerLedger') return { customer, transactions: [], summary: { opening_balance: 0, total_debit: 0, total_credit: 0, closing_balance: 0, closing_status: 'Settled' } };
        if (name === 'createTransaction') return { transaction: { id: 1, transaction_code: 'TRX-000001' } };
        if (name === 'getUsers') return [{ id: 1, name: 'Admin', username: 'admin', role: 'Admin' }, { id: 2, name: 'Staff', username: 'staff', role: 'Staff' }];
        if (name.includes('Report')) return report;
        if (name === 'authenticate') return args[1] === 'correct' ? { id: 1, name: 'Admin', role: 'Admin' } : null;
        if (name.startsWith('get')) return [];
        return {};
      }});
      undefined;
    `);
    await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname, 'renderer/js/app.js'), 'utf8'));
    const result = await win.webContents.executeJavaScript(`(async () => {
      const assert = (ok, message) => { if (!ok) throw new Error(message); };
      const tick = () => new Promise(resolve => setTimeout(resolve, 30));
      const click = async selector => { assert(document.querySelector(selector), 'Missing selector: ' + selector); document.querySelector(selector).click(); await tick(); };
      const submit = async id => { document.getElementById(id).dispatchEvent(new Event('submit', { cancelable: true })); await tick(); };
      const value = (id, value) => document.getElementById(id).value = value;
      await tick();
      for (const button of document.querySelectorAll('button')) {
        if (button.hasAttribute('onclick') || button.hasAttribute('data-close-modal') || bound.has(button.id + ':click')) continue;
        assert(button.type === 'submit' && button.form && bound.has(button.form.id + ':submit'), 'Unconnected button: ' + (button.id || button.textContent.trim()));
      }
      for (const view of ['customers', 'transactions', 'reports', 'backup', 'settings', 'dashboard']) {
        await click('[data-view="' + view + '"]');
        assert(document.getElementById('view-' + view).classList.contains('active-view'), 'Navigation failed: ' + view);
        assert(getComputedStyle(document.getElementById('view-' + view)).display !== 'none', 'View is hidden: ' + view);
      }
      await click('#btn-open-new-customer-modal');
      assert(document.getElementById('modal-new-customer').classList.contains('active-modal'), 'New customer failed');
      value('cust-new-name', 'Double submit customer');
      const customerSaves = calls.filter(c => c[0] === 'createCustomer').length;
      const customerSaveOne = handleSaveCustomer();
      const customerSaveTwo = handleSaveCustomer();
      await Promise.all([customerSaveOne, customerSaveTwo]);
      assert(calls.filter(c => c[0] === 'createCustomer').length === customerSaves + 1, 'Customer saved twice');
      await click('[data-close-modal="modal-new-customer"]');
      await click('#btn-quick-new-trx');
      assert(document.getElementById('modal-new-transaction').classList.contains('active-modal'), 'Quick transaction failed');
      value('trx-customer-select', '1'); value('trx-credit', '10'); value('trx-details', 'Double submit transaction');
      const transactionSaves = calls.filter(c => c[0] === 'createTransaction').length;
      const transactionSaveOne = handleSaveTransaction();
      const transactionSaveTwo = handleSaveTransaction();
      await Promise.all([transactionSaveOne, transactionSaveTwo]);
      assert(calls.filter(c => c[0] === 'createTransaction').length === transactionSaves + 1, 'Transaction saved twice');
      await click('[data-close-modal="modal-new-transaction"]');
      await openEditTransactionModal(5);
      assert(document.getElementById('trx-credit').value === '125.00', 'Edit did not prefill amount');
      assert(document.getElementById('trx-customer-select').disabled, 'Editing allowed customer reassignment');
      value('trx-credit', '130.00');
      closeModal('modal-new-transaction');
      assert(document.getElementById('modal-new-transaction').classList.contains('active-modal'), 'Unsaved edit dismissed without confirmation');
      await handleSaveTransaction();
      assert(calls.some(c => c[0] === 'updateTransaction' && c[1] === 5 && c[2].amount === 13000), 'Transaction edit not saved');
      await click('#btn-quick-new-trx');
      assert(!document.getElementById('trx-customer-select').disabled, 'New transaction customer still locked');
      value('trx-details', 'Discard this draft');
      window.confirmAnswer = true;
      closeModal('modal-new-transaction');
      window.confirmAnswer = false;
      assert(!document.getElementById('modal-new-transaction').classList.contains('active-modal'), 'Discard confirmation did not close form');
      await click('[data-view="transactions"]');
      value('filter-trx-customer', '1'); value('filter-trx-min', '10'); value('filter-trx-max', '20'); value('filter-trx-payment', 'Cash');
      await loadTransactions();
      assert(calls.some(c => c[0] === 'getAllTransactions' && c[1].customer_id === '1' && c[1].amount_min === 1000 && c[1].amount_max === 2000 && c[1].payment_method === 'Cash'), 'Advanced filters not passed to API');
      await click('#btn-clear-trx-filters');
      assert(document.getElementById('filter-trx-min').value === '', 'Clear did not reset advanced filters');
      await click('[data-view="customers"]');
      await click('#tab-cust-archived');
      assert(!document.getElementById('customers-table-body').textContent.includes('Test Customer'), 'Active customer leaked into Archived tab');
      assert(document.getElementById('customers-table-body').textContent.includes('Archived Customer'), 'Archived customer missing');
      await click('#tab-cust-active');
      await click('#customers-table-body button');
      assert(document.getElementById('view-customer-khata').classList.contains('active-view'), 'Dynamic Khata button failed');
      await click('#btn-khata-print-statement');
      await click('#btn-export-statement-csv');
      await click('#btn-print-statement-now');
      assert(document.getElementById('modal-statement').classList.contains('print-target'), 'Print target missing');
      await click('[data-close-modal="modal-statement"]');
      await click('[data-view="reports"]');
      await click('[data-report="daily"]');
      assert(calls.some(c => c[0] === 'getAllTransactions' && c[1].date_from === c[1].date_to), 'Daily report did not filter transactions');
      await click('[data-report="custom"]');
      value('report-date-input', '2026-01-01'); value('report-date-to-input', '2026-01-31');
      await click('#btn-generate-custom-report');
      assert(calls.some(c => c[0] === 'getAllTransactions' && c[1].date_to === '2026-01-31'), 'Date range report failed');
      await click('#btn-export-report-csv');
      assert(downloads.length === 2, 'CSV exports failed');
      await click('[data-report="balance"]');
      assert(document.getElementById('report-sheet-header-row').textContent.includes('Current Balance'), 'Balance report header not restored');
      await click('[data-view="settings"]');
      await click('#tab-settings-security');
      value('password-current', 'old-secret'); value('password-new', 'new-secret'); value('password-confirm', 'different');
      await submit('form-change-password');
      assert(document.getElementById('password-result').textContent.includes('do not match'), 'Password mismatch not detected');
      value('password-confirm', 'new-secret');
      await submit('form-change-password');
      assert(calls.some(c => c[0] === 'changePassword' && c[1] === 'old-secret' && c[2] === 'new-secret'), 'Password change not submitted');
      assert(document.getElementById('password-new').value === '', 'Password fields not cleared');
      await click('#btn-open-new-user-modal');
      value('new-user-fullname', 'Test'); value('new-user-username', 'test'); value('new-user-password', 'example');
      await submit('form-new-user');
      assert(calls.some(c => c[0] === 'createUser' && c[1] === 'Test'), 'Create user failed');
      await click('#users-table-body button'); await click('#btn-confirm-action-submit');
      assert(calls.some(c => c[0] === 'deleteUser' && c[1] === 2), 'Delete user failed');
      await click('#btn-remove-logo');
      assert(calls.some(c => c[0] === 'updateSettings' && c[1].logo_base64 === ''), 'Remove logo failed');
      await click('#btn-logout');
      assert(document.getElementById('app-container').inert, 'Logout failed');
      closeModal('modal-app-login');
      assert(document.getElementById('modal-app-login').classList.contains('active-modal'), 'Login can be dismissed');
      value('login-username', 'admin'); value('login-password', 'wrong'); await submit('form-login');
      assert(document.getElementById('login-error-msg').style.display === 'block', 'Invalid login missing error');
      value('login-password', 'correct'); await submit('form-login');
      assert(!document.getElementById('app-container').inert, 'Login failed');
      showToast('<img src=x onerror="window.toastInjected=true">');
      assert(!document.querySelector('#toast-container img'), 'Toast interpreted HTML');
      await click('[data-view="settings"]');
      await click('#tab-settings-profile');
      value('cfg-business-name', 'Unsaved change');
      await click('[data-view="customers"]');
      assert(document.getElementById('view-settings').classList.contains('active-view'), 'Unsaved profile navigation was not stopped');
      window.confirmAnswer = true;
      await click('[data-view="customers"]');
      assert(document.getElementById('view-customers').classList.contains('active-view'), 'Confirmed profile discard did not navigate');
      assert(!failures.length, failures.join('; '));
      return { buttons: document.querySelectorAll('button').length, downloads, errors: failures, result: 'PASS' };
    })()`);
    console.log(JSON.stringify(result));
    fs.writeFileSync(resultPath, JSON.stringify(result, null, 2));
    clearTimeout(timeout);
    app.exit(0);
  } catch (err) { fs.writeFileSync(resultPath, JSON.stringify({ error: err.message })); console.error(err); app.exit(1); }
});
